#!/usr/bin/python

import random
import argparse


#Define arguments:

parser= argparse.ArgumentParser()
parser.add_argument("-tl", "--total", type=int, help="Choose the length of the original sequence")
parser.add_argument("-sh", "--short", type=int, help="Choose the lenght of short sequences")
args = parser.parse_args()

#Define variables

TOTAL=args.total
SHORT=args.short
BASES = ["A", "C", "T", "G"]

#Generate sequence 

SEQUENCE= ''.join(random.choice(BASES) for i in range(TOTAL))

#Split sequence

SEQCHUNK= [SEQUENCE[i:i+SHORT] for i in range(0, len(SEQUENCE),SHORT)]  


def.gccont(SEQCHUNK)

countG=SEQCHUNK.count ("G")
countC=	SEQCHUNK.count ("C") 

GCCOUNT= SEQCHUNK.count ("G") + SEQCHUNK.count("C")
	for seq in SEQCHUNK:
		GC=(countG + countC)/TOTAL
	return (GC)






